# Site settings
title: Harry Cutts
author: Harry Cutts
copyrightYear: 2014
email: your-email@domain.com
description:
    I'm a Computer Science undergraduate at the University of Southampton,
    interested in User Experience design, information security and robotics.
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
exclude:
    - node_modules
